### ISSUE TITLE
Add Websocket dependencies

### ISSUE THREAD

**Issue by ransTomTer** [POWERLANE-TEAM/emplo-hrms#3]
https://laravel.com/docs/11.x/broadcasting

Follow guide https://youtu.be/tExUWmF6wNM?list=PLwAKR305CRO9rlj-U9oOi4m2sQaWN6XA8&t=1002

- [x] #24
- [x] #20
- [x] #21
- [x] #22
- [x] #23

**Comment by Carl-Tabuso** [comment]
You can turn each task into its own new issue.

**Comment by Carl-Tabuso** [comment]
Are you going to use a laravel package for websocket? I strongly suggest [reverb](https://laravel.com/docs/11.x/reverb)
